### ISSUE TITLE
Error 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by PrometheusDante** [SayanoAI/Comfy-RVC#1]
Hello there, I just tried out your example workflows and ran into this error:

> Error occurred when executing UVR5Node:
> 
> module 'numpy' has no attribute 'float'.
> `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> 
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\custom_nodes\uvr.py", line 80, in split
>     vocals, instrumental, input_audio = model.run_inference(audio_path,format=kwargs.get("format"))
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\uvr5_cli.py", line 53, in run_inference
>     return_dict = self.model.run_inference(audio_path)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\lib\separators.py", line 244, in run_inference
>     return_dict = self.process_audio(y_spec_m,v_spec_m,input_high_end,input_high_end_h)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\lib\separators.py", line 181, in process_audio
>     pool.apply(self.process_vocals, args=(v_spec_m,input_high_end,input_high_end_h,return_dict))
>   File "multiprocessing\pool.py", line 360, in apply
>   File "multiprocessing\pool.py", line 774, in get
>   File "multiprocessing\pool.py", line 125, in worker
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\lib\separators.py", line 152, in process_vocals
>     wav_vocals = spec_utils.cmb_spectrogram_to_wave(
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\lib\uvr5_pack\spec_utils.py", line 330, in cmb_spectrogram_to_wave
>     wave = librosa.resample(spectrogram_to_wave(spec_s, bp['hl'], mp.param['mid_side'],mp.param['mid_side_b2'], mp.param['reverse']), orig_sr=bp['sr'], target_sr=sr, res_type=wav_resolution)
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\Comfy-RVC\lib\uvr5_pack\spec_utils.py", line 269, in spectrogram_to_wave
>     wave_left = librosa.istft(spec_left, hop_length=hop_length)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
>     dtype = util.dtype_c2r(stft_matrix.dtype)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
>     return f(*args, **kwargs)
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
>     np.dtype(complex): np.dtype(np.float).type,
>   File "D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
>     raise AttributeError(__former_attrs__[attr])

I've installed through the comfyui manager and after I got this error I manually went to the custom node location and installed its requirements with:

pip install -r requirements.txt

which results in another error, because of using python 3.12

> ERROR: Failed building wheel for faiss-cpu

So I've done this instead:

`py -3.10 -m pip install -r requirements.txt`

and it installed without issues.

After successfully installing the requirements it still results in the same numpy error when running the workflow. All nodes and the manager are up to date of course.

Thank you very much in advance and for implementing RVC in comfy!

**Comment by SayanoAI** [comment]
Looks like the error is due to this: https://github.com/Anjok07/ultimatevocalremovergui/issues/1016#issuecomment-1868489252

Try downgrading numpy to <1.24 and let me know if that works.

**Comment by PrometheusDante** [comment]
I've tried manually downgrading to 1.23, but it ran into the same error. But then I installed your new updated version and it didn't throw the float error anymore. So thanks for the fix!
