### ISSUE TITLE
Get a error llike `unknown args: ['--listen']`

### ISSUE THREAD

**Issue by Icedcocon** [SayanoAI/Comfy-RVC#10]
Similar bug exists in latest ComfyUI, but more severe when ComfyUI-RVC.

```bash
main.py: error: unrecognized arguments: --listen --gpu-only
```

Then ComfyUI no longer works.

Comfy-RVC does a good job in this regard. ComfyUI can work normally, but it will still prompt the following information:

```bash
unknown args: ['--listen']
```

I don't understand why this occurs. Is it because the wrong main.py is used due to the addition of sys.path, or is it for other reasons? I hope you can answer my questions

**Comment by SayanoAI** [comment]
This is printed by the config.py file I copied from mainline rvc repo, it can be safely ignored.

**Comment by Icedcocon** [comment]
> This is printed by the config.py file I copied from mainline rvc repo, it can be safely ignored.


Thanks for your answer.
