### ISSUE TITLE
Training Failed

### ISSUE THREAD

**Issue by skimy2023** [SayanoAI/Comfy-RVC#13]
The phenomenon is a purple box, and I don't quite understand it.
This is a new model. For example, I named it "CXK" in "Process RVC Dataset", then why would I be prompted that this model does not exist? This is obviously a new model that I want to train.

2024-09-09 05:00:50,933 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\Comfy-RVC\custom_nodes\rvc_nodes.py", line 482, in train_model
    assert os.path.isfile(model_path), f"Failed to train model {model_path}..."
AssertionError: Failed to train model E:\ComfyUI-aki-v1.3\models\RVC\cxk_48k.pth...

2024-09-09 05:00:50,934 - root - INFO - Prompt executed in 12.04 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":18,"last_link_id":31,"nodes":[{"id":6,"type":"RVCNode","pos":{"0":945.4000854492188,"1":-349.9999694824219},"size":{"0":418.1999816894531,"1":166},"flags":{},"order":7,"mode":0,"inputs":[{"name":"audio","type":"AUDIO,VHS_AUDIO","link":12,"label":"audio"},{"name":"model","type":"RVC_MODEL","link":23,"label":"model"},{"name":"hubert_model","type":"HUBERT_MODEL","link":24,"label":"hubert_model"},{"name":"pitch_extraction_params","type":"PITCH_EXTRACTION","link":25,"label":"pitch_extraction_params"}],"outputs":[{"name":"VHS_AUDIO","type":"VHS_AUDIO","links":[13],"slot_index":0,"shape":3,"label":"VHS_AUDIO"}],"properties":{"Node name for S&R":"RVCNode"},"widgets_values":[0,"flac",true]},{"id":10,"type":"UVR5Node","pos":{"0":573.4000854492188,"1":-355.9999694824219},"size":{"0":315,"1":150},"flags":{},"order":4,"mode":0,"inputs":[{"name":"audio","type":"AUDIO,VHS_AUDIO","link":11,"label":"audio"}],"outputs":[{"name":"primary_stem","type":"VHS_AUDIO","links":[12],"slot_index":0,"shape":3,"label":"primary_stem"},{"name":"secondary_stem","type":"VHS_AUDIO","links":[14],"slot_index":1,"shape":3,"label":"secondary_stem"}],"properties":{"Node name for S&R":"UVR5Node"},"widgets_values":["UVR/HP5-vocals+instrumentals.pth",true,10,"flac"]},{"id":11,"type":"MergeAudioNode","pos":{"0":1431.4000244140625,"1":-346.9999694824219},"size":{"0":315,"1":166},"flags":{},"order":8,"mode":0,"inputs":[{"name":"audio1","type":"AUDIO,VHS_AUDIO","link":13,"label":"audio1"},{"name":"audio2","type":"AUDIO,VHS_AUDIO","link":14,"label":"audio2"},{"name":"audio3_opt","type":"AUDIO,VHS_AUDIO","link":null,"label":"audio3_opt"},{"name":"audio4_opt","type":"AUDIO,VHS_AUDIO","link":null,"label":"audio4_opt"}],"outputs":[{"name":"vhs_audio","type":"VHS_AUDIO","links":null,"slot_index":0,"shape":3,"label":"vhs_audio"},{"name":"audio","type":"AUDIO","links":[],"slot_index":1,"shape":3,"label":"audio"}],"properties":{"Node name for S&R":"MergeAudioNode"},"widgets_values":["None","median",true]},{"id":9,"type":"RVC-Studio.LoadAudio","pos":{"0":315.40008544921875,"1":-363.9999694824219},"size":{"0":210,"1":146},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"audio_name","type":"STRING","links":null,"shape":3,"label":"audio_name"},{"name":"vhs_audio","type":"VHS_AUDIO","links":[11],"slot_index":1,"shape":3,"label":"vhs_audio"},{"name":"audio","type":"AUDIO","links":null,"shape":3,"label":"audio"}],"properties":{"Node name for S&R":"RVC-Studio.LoadAudio"},"widgets_values":["Tank - 千年泪.flac",44100,"image"]},{"id":5,"type":"LoadHubertModel","pos":{"0":-403,"1":402},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"hubert_model","type":"HUBERT_MODEL","links":[28],"slot_index":0,"shape":3,"label":"hubert_model"}],"properties":{"Node name for S&R":"LoadHubertModel"},"widgets_values":["content-vec-best.safetensors"]},{"id":17,"type":"RVCProcessDatasetNode","pos":{"0":-8,"1":176},"size":{"0":337.6000061035156,"1":290},"flags":{},"order":5,"mode":0,"inputs":[{"name":"hubert_model","type":"HUBERT_MODEL","link":28,"label":"hubert_model"},{"name":"pitch_extraction_params","type":"PITCH_EXTRACTION","link":29,"label":"pitch_extraction_params"},{"name":"audio_processor","type":"AUDIO_PROCESSOR","link":null,"label":"audio_processor"}],"outputs":[{"name":"rvc_dataset_pipe","type":"RVC_DATASET_PIPE","links":[30],"slot_index":0,"shape":3,"label":"rvc_dataset_pipe"}],"properties":{"Node name for S&R":"RVCProcessDatasetNode"},"widgets_values":["cxk","蔡徐坤.zip","48k",12,3,0.5,0.9500000000000001,0.01,"image"]},{"id":3,"type":"LoadPitchExtractionParams","pos":{"0":-387,"1":130},"size":{"0":315,"1":202},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"pitch_extraction_params","type":"PITCH_EXTRACTION","links":[29],"slot_index":0,"shape":3,"label":"pitch_extraction_params"}],"properties":{"Node name for S&R":"LoadPitchExtractionParams"},"widgets_values":["rmvpe+",true,0.75,48000,0.25,0.25,160]},{"id":18,"type":"RVCTrainParamsNode","pos":{"0":-45,"1":-152},"size":{"0":315,"1":250},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"rvc_training_params","type":"RVC_TRAINING_PARAMS","links":[31],"shape":3,"label":"rvc_training_params","slot_index":0}],"properties":{"Node name for S&R":"RVCTrainParamsNode"},"widgets_values":[3,45,1,2,0,0,0,0,0]},{"id":15,"type":"RVCTrainModelNode","pos":{"0":380,"1":87},"size":{"0":506.4000244140625,"1":430},"flags":{},"order":6,"mode":0,"inputs":[{"name":"rvc_dataset_pipe","type":"RVC_DATASET_PIPE","link":30,"label":"rvc_dataset_pipe"},{"name":"rvc_training_params","type":"RVC_TRAINING_PARAMS","link":31,"label":"rvc_training_params"}],"outputs":[{"name":"model","type":"RVC_MODEL","links":[23],"slot_index":0,"shape":3,"label":"model"},{"name":"model_name","type":"STRING","links":null,"shape":3,"label":"model_name"},{"name":"hubert_model","type":"HUBERT_MODEL","links":[24],"slot_index":2,"shape":3,"label":"hubert_model"},{"name":"pitch_extraction_params","type":"PITCH_EXTRACTION","links":[25],"slot_index":3,"shape":3,"label":"pitch_extraction_params"}],"properties":{"Node name for S&R":"RVCTrainModelNode"},"widgets_values":["0",200,100,"pretrained_v2/f0G40k.pth","pretrained_v2/f0D40k.pth","pretrained_v2/D_DMR-V1-32k-f0.pth",false,false,false,true,true,50,1,1]}],"links":[[11,9,1,10,0,"AUDIO,VHS_AUDIO"],[12,10,0,6,0,"AUDIO,VHS_AUDIO"],[13,6,0,11,0,"AUDIO,VHS_AUDIO"],[14,10,1,11,1,"AUDIO,VHS_AUDIO"],[23,15,0,6,1,"RVC_MODEL"],[24,15,2,6,2,"HUBERT_MODEL"],[25,15,3,6,3,"PITCH_EXTRACTION"],[28,5,0,17,0,"HUBERT_MODEL"],[29,3,0,17,1,"PITCH_EXTRACTION"],[30,17,0,15,0,"RVC_DATASET_PIPE"],[31,18,0,15,1,"RVC_TRAINING_PARAMS"]],"groups":[{"title":"Model Trainer","bounding":[-413,45,1303,466],"color":"#b06634","font_size":24,"flags":{}},{"title":"Basic Voice Changer","bounding":[305,-438,1451,267],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":1.1,"offset":[285.8904644461148,186.55384639246716]}},"version":0.4}

**Comment by SayanoAI** [comment]
You are using a 40k pretrain to train a 48k model. Try changing to a 48k pretrain or lower your sr to 40k.
