### ISSUE TITLE
how to input audio?

### ISSUE THREAD

**Issue by bob83111** [SayanoAI/Comfy-RVC#5]
I couldn't input audio into the audio input ports of any nodes. The audio ports cannot be connected, regardless of whether it is a WAV file or an MP3 file. Could you please tell me the reason for this? How should I solve this problem?

**Comment by SayanoAI** [comment]
Can you show me what your workflow looks like? You might have to right click on the node and click "fix nodes".

**Comment by bob83111** [comment]
![0721142652](https://github.com/user-attachments/assets/00084a1d-2ccc-4f53-b6fa-7fe29b804cd0)
I have two "load audio" nodes. Please see the image: Node A is summoned by clicking the "audio" input port of "vocal removal," while Node B is summoned from the right-click menu (as shown, it is in the root directory of the audio menu, not under the RVC-studio sub-options). Node A can connect to the vocal removal (and other nodes that require audio input), but Node B cannot. I personally suspect that it might be due to a conflict in node names. My ComfyUI is an integrated package created by someone else, not self-deployed. Additionally, where should I place the UVR models for vocal separation, the singer voice models, and the whisper models? Lastly, can this node be used to train vocal models?  I would appreciate your guidance. Thank you very much.

**Comment by bob83111** [comment]
![微信图片_20240721190319](https://github.com/user-attachments/assets/575fe13e-b5b1-499d-9161-02e1cbafa8d6)
Your script forces downloading the model from huggingface.co. Could you please tell me which file I should modify to change this setting? My network is restricted, and I can't download it. Later, I individually accessed /sayanoai/rvc-studio and found only one safetensors model of over 300MB. Actually, I already have these models, but I don't know where to place them.

**Comment by SayanoAI** [comment]
Yep, I suspect there's a naming conflict somewhere with the Load Audio Node. All the nodes that work with Comfy-RVC should be organized under the RVC-Studio tab in the menu.

Your RVC models should go in ComfyUI\models\RVC, UVR models go in ComfyUI\models\UVR.

**Comment by PrometheusDante** [comment]
The example workflows are outdated in that regard, but I found fitting conversion nodes from this custom node pack :
[ComfyUI-VideoHelperSuite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite)
This is the reworked version of the complete example, it is a little customized already, but does not use any other nodes than that videohelper suite and all settings are at the default pretty much.

![workflow](https://github.com/user-attachments/assets/1ae8ada7-bc9a-4d9a-b4a6-b285badec4b8)


[complete-ai-voice-changer_custom.json](https://github.com/user-attachments/files/16401525/complete-ai-voice-changer_custom.json)

**Comment by SayanoAI** [comment]
Thanks for that, the latest update should have an extra output that works fine with the regular comfyui audio: 
![image](https://github.com/user-attachments/assets/f9bcd79c-1caf-4430-9b41-1fa7e688f524)
