### ISSUE TITLE
about connection issue

### ISSUE THREAD

**Issue by bob83111** [SayanoAI/Comfy-RVC#6]
A more peculiar issue is the network problem. If I open it using the launcher, it gives an error (raw.githubusercontent.com:443) and cannot download. However, if I download it manually, there is no issue. The file for downloading the model should be custom_nodes\settings\downloader.py, right? My method is to paste the filename into the address bar, and it works. As shown in the picture, I don't understand Python very well.
![微信图片_20240721210221](https://github.com/user-attachments/assets/116eb99c-bc0f-491e-9ff6-a4f1dfa3c94e)
![微信图片_20240721211451](https://github.com/user-attachments/assets/340f46f1-c2aa-45c2-ba66-b79b40a5c6c7)
![微信图片_20240721211110](https://github.com/user-attachments/assets/0948120e-f819-425b-b1f4-0439be23dbc1)

**Comment by SayanoAI** [comment]
Yep, all the built-in models can be found here: https://huggingface.co/datasets/SayanoAI/RVC-Studio/tree/main

The repo is structured as if it's inside the ComfyUI/model folder. So [content-vec-best.safetensors](https://huggingface.co/datasets/SayanoAI/RVC-Studio/blob/main/content-vec-best.safetensors) should be in the main model folder while [UVR-DeNoise.pth](https://huggingface.co/datasets/SayanoAI/RVC-Studio/blob/main/UVR/UVR-DeNoise.pth) should be in the model/UVR folder.

**Comment by bob83111** [comment]
I am very confused. I am sure I placed the models in the correct path, but they still can't run and indicate a network connection issue. This problem is not only with the UVR series models but also with the RVC models and the pretrained_v2 models. I also placed the content-vec-best.safetensors model in the custom_nodes\Comfy-RVC\models directory. Why isn't the program calling the local models?
![微信图片_20240722200959](https://github.com/user-attachments/assets/cdab6623-c294-4891-9029-3b7ba83dd6b2)
![Uploading 微信图片_20240722200953.png…]()

**Comment by bob83111** [comment]
![image](https://github.com/user-attachments/assets/0363076a-b8a7-413d-8e89-5bd2de29e43c)

**Comment by SayanoAI** [comment]
Put them in the same folder you put your checkpoints, controlnets, and loras (which should be ComfyUI/models by default).

**Comment by bob83111** [comment]
![微信图片_20240728001813](https://github.com/user-attachments/assets/c5056fb2-76e9-4f14-8d20-d3a83dfc15fc)
[](url)
![微信图片_20240728001900](https://github.com/user-attachments/assets/152f84f1-9403-4f73-8dbd-b233c6d1f48e)

Sorry, there's a new problem again
