### ISSUE TITLE
Index files

### ISSUE THREAD

**Issue by PrometheusDante** [SayanoAI/Comfy-RVC#7]
Hello there, I still have a few issues with the nodes, such as only being able to run the workflow once and having to restart ComfyUI in order to work again, but there is also another minor issue concerning the index files.

Custom RVC models are detected, can be selected and work, but index files do not appear in the dropdown menu.
I put all the files in their respective locations of course into `model\RVC` and `models\RVC\.index`

**Comment by bob83111** [comment]
> Hello there, I still have a few issues with the nodes, such as only being able to run the workflow once and having to restart ComfyUI in order to work again, but there is also another minor issue concerning the index files.
> 
> Custom RVC models are detected, can be selected and work, but index files do not appear in the dropdown menu. I put all the files in their respective locations of course into `model\RVC` and `models\RVC\.index`

me too

**Comment by bob83111** [comment]
Moreover, there are errors and ComfyUI will crashes and disconnects when loading the default timbre model and index. Another key issue is the inability to load hubert_base.pt, while content-vec-best.safetensors can be loaded. This problem is crucial, as the inference quality of hubert_base.pt is actually better than that of content... I hope you can help me resolve this issue. Thank you very much.
![360截图20240731015437271](https://github.com/user-attachments/assets/5ff739ab-67a3-4743-a416-89aeb44fbca2)

![image](https://github.com/user-attachments/assets/6b33c54f-c7d2-4279-8092-c942af268fda)

**Comment by SayanoAI** [comment]
Are you running this on the cloud? It looks like you've added some kind of sentry integration. The nodes will download any missing models as you run it so it might crash if you have some firewall up.

**Comment by SayanoAI** [comment]
> Hello there, I still have a few issues with the nodes, such as only being able to run the workflow once and having to restart ComfyUI in order to work again, but there is also another minor issue concerning the index files.
> 
> Custom RVC models are detected, can be selected and work, but index files do not appear in the dropdown menu. I put all the files in their respective locations of course into `model\RVC` and `models\RVC\.index`

make sure the index files end with .index (not .npy) and that you added them to your **ComfyUI/models/RVC** folder (**not ComfyUI/custom_nodes/Comfy-RVC/models/RVC**)

**Comment by jixiangge111** [comment]
Not using the cloud, my ComfyUI is a one-click integration package made by a famous Chinese expert (as shown in the picture), and it runs locally. Many people in China use his integration package for Stable Diffusion. China has internet restrictions, so we generally use proxy servers to access websites like Hugging Face, but sometimes there are issues.
I'm describing it to you in the form of a picture, sorry for the trouble.
![launcher](https://github.com/user-attachments/assets/433685ea-e290-40d6-8da8-910e00c2769d)
![Uploading github_indexappear.png…]()
![github_indexcrash](https://github.com/user-attachments/assets/12afae71-d0c8-4e15-8f99-eb38ecd5cd6c)
![hubert](https://github.com/user-attachments/assets/a1746630-7c59-4128-9314-ce851a2e422b)

**Comment by bob83111** [comment]
Not using the cloud, my ComfyUI is a one-click integration package made by a famous Chinese expert (as shown in the picture), and it runs locally. Many people in China use his integration package for Stable Diffusion. China has internet restrictions, so we generally use proxy servers to access websites like Hugging Face, but sometimes there are issues.
I'm describing it to you in the form of a picture, sorry for the trouble.

![launcher](https://github.com/user-attachments/assets/01a56e3b-670c-4308-8f4f-140e6618bdd6)

![github_indexappear](https://github.com/user-attachments/assets/cb8cb90b-7853-499d-9903-20c2311a4022)

![github_indexcrash](https://github.com/user-attachments/assets/94858fb6-1568-4d7a-b05d-a77c8280b5a7)

![hubert](https://github.com/user-attachments/assets/50b81fbd-8292-4691-9c01-967f7dd04b18)

**Comment by SayanoAI** [comment]
The latest comfyui update broke something in the faiss library so you will have to just run it without the index file.

You can try clicking the refresh button to get your voice models to show up: 
![image](https://github.com/user-attachments/assets/6a2daec1-fb3c-45d1-b695-3c48e5a796c1)

**Comment by bob83111** [comment]
Alright, I found that the output from this node is a bit different from my other GUI version of RVC. Additionally, is it true that this node cannot train a vocal model?

**Comment by SayanoAI** [comment]
The code for training is in the repo, I haven't made any nodes for that yet. The hubert_model.pt uses fairseq to load, which causes a lot of problems with various packages. This is why I recommend the content_vec that lengyue (https://huggingface.co/lengyue233/content-vec-best/tree/main) converted.

**Comment by bob83111** [comment]
okay,thanks a lot

**Comment by SayanoAI** [comment]
The index file issue has been fixed in the latest release
