### ISSUE TITLE
about monotonic_align?

### ISSUE THREAD

**Issue by jixiangge111** [SayanoAI/Comfy-RVC#8]
![image](https://github.com/user-attachments/assets/01d77123-5ac4-4ca9-b58c-b9efb9ec3835)
i have a issue when i install the list of requirements.txt.... could y tell me how to deal with?

**Comment by SayanoAI** [comment]
Please refer to this issue: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1103

How are you running this? Which python version are you using?

**Comment by jixiangge111** [comment]
> Please refer to this issue: [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1103](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1103)
> 
> How are you running this? Which python version are you using?

thanks,i got it: to install vc++
